name: lms
services:
  mariadb:
    image: mariadb:10.6
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed # Temporary fix for MariaDB 10.6
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?set in .env}
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -uroot -p$${MYSQL_ROOT_PASSWORD} --silent"]
      interval: 5s
      timeout: 3s
      retries: 30
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 30
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  frappe:
    # Pin via BENCH_IMAGE in .env, defaulting to version-14
    image: ${BENCH_IMAGE:-frappe/bench:version-14}
    command: bash /workspace/init.sh
    environment:
      - SHELL=/bin/bash
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - SITE_NAME=${SITE_NAME:-lms.localhost}
      - SITE_HOST=${SITE_HOST:-}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - DEVELOPER_MODE=${DEVELOPER_MODE:-0}
    working_dir: /home/frappe
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - .:/workspace
      - sites-data:/home/frappe/frappe-bench/sites
    ports:
      - 127.0.0.1:8000:8000
      - 127.0.0.1:9000:9000
    logging:
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  mariadb-data:
  sites-data: